import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';
import {parseTransitText,literalStopoverPatch} from '../overlay/server/providers/tdxParse.js';
import {isClassificationOnly,isFreeTextModel,finalTextOptions} from '../overlay/server/providers/freeTextModels.js';
import {streamTaiwanChat} from '../overlay/server/providers/taiwanChat.js';
import {buildTransitRecovery} from '../overlay/src/taiwan/transitRecovery.js';
import {TRANSIT_EXAMPLES,normalizeTripRequest} from '../overlay/src/taiwan/transitPlanning.js';
const now=Date.parse('2026-10-06T04:00:00Z'),profiles=[{type:'adult',quantity:1},{type:'child',quantity:1}];
const metadata=id=>({id,name:id,pricing:{prompt:'0',completion:'0'},architecture:{output_modalities:['text']},supported_parameters:[]});
const base=normalizeTripRequest({farePreference:{passengerProfiles:profiles}});
test('classifier catalog and response are never useful assistant outputs',()=>{assert.equal(isFreeTextModel(metadata('nvidia/nemotron-3.5-content-safety:free')),false);for(const text of ['User Safety: safe','safe','Safety: unsafe'])assert.equal(isClassificationOnly(text),true);assert.equal(isClassificationOnly('已載入圖層可供查詢，尚未執行計算。'),false);});
test('example 5 local parsing preserves mixed passengers, stop and deadline',async()=>{const r=await parseTransitText(TRANSIT_EXAMPLES[4][1],base,{now:()=>now,credential:()=>{throw Error('must not require model');}});assert.equal(r.request.origin,'宜蘭縣政府');assert.equal(r.request.destination,'台北車站');assert.equal(r.request.waypoints[0].location,'羅東車站');assert.equal(r.request.waypoints[0].stayDurationMinutes,30);assert.equal(r.request.arrivalDeadline,'2026-10-06T13:00:00+08:00');assert.deepEqual(r.request.farePreference.passengerProfiles,profiles);assert.equal(r.needsClarification,true);});
test('explicit tomorrow stopover can proceed without a classifier',()=>{const r=literalStopoverPatch(TRANSIT_EXAMPLES[4][1].replace('我早上','我明天早上'),now);assert.equal(r.needsClarification,false);assert.equal(r.patch.departureTime,'2026-10-07T09:00:00+08:00');});
test('three corrections preserve stop and tickets and never mutate request',()=>{const stop=literalStopoverPatch(TRANSIT_EXAMPLES[4][1],now);const request=normalizeTripRequest({...base,...stop.patch}),before=structuredClone(request),r=buildTransitRecovery(request,new Error('指定出發時間已過'),now);assert.equal(r.suggestions.length,3);assert.equal(r.suggestions[0].patch.departureTime,'2026-10-07T09:00:00+08:00');assert.equal(r.suggestions[0].patch.arrivalDeadline,'2026-10-07T13:00:00+08:00');assert.deepEqual(r.request.farePreference.passengerProfiles,profiles);assert.deepEqual(request,before);});
test('parse rotates past three models and reports actual progress',async()=>{const tried=[],progress=[];const result=await parseTransitText('從宜蘭去台北，請比較最少轉乘。',base,{now:()=>now,credential:()=> 'synthetic',onProgress:v=>progress.push(v),fetcher:async(url,options)=>{if(url.endsWith('/models'))return Response.json({data:['one','two','three','four'].map(metadata)});const p=JSON.parse(options.body);tried.push(p.model);return Response.json({choices:[{message:{content:tried.length<4?'User Safety: safe':JSON.stringify({patch:{origin:'宜蘭',destination:'台北'},intent:'plan',needsClarification:false,questions:[],explanation:'已理解'})}}]});}});assert.equal(result.model,'four');assert.equal(tried.length,4);assert.equal(progress.length,4);assert.deepEqual(result.request.farePreference.passengerProfiles,profiles);});
test('cancel stops parsing before contacting another provider',async()=>{const abort=new AbortController();let calls=0;await assert.rejects(parseTransitText('請幫忙安排複雜旅程',base,{signal:abort.signal,credential:()=> 'synthetic',fetcher:async url=>{calls++;abort.abort();return Response.json({data:[metadata('one')]});}}));assert.equal(calls,1);});
test('generic streaming rejects safety-only first three models and completes fourth',async()=>{const original=globalThis.fetch,calls=[],res=new EventEmitter();res.destroyed=false;res.writableEnded=false;res.output='';res.writeHead=()=>{};res.write=v=>{res.output+=v;};res.end=()=>{res.writableEnded=true;};globalThis.fetch=async(url,options)=>{if(url.endsWith('/models'))return Response.json({data:['qa1','qa2','qa3','qa4'].map(metadata)});const model=JSON.parse(options.body).model;calls.push(model);const text=calls.length<4?'User Safety: safe':'已載入的圖層可用於屬性統計與空間分析，尚未執行計算的部分會明確標示為待驗證推論。';return new Response(`data: ${JSON.stringify({model,choices:[{delta:{content:text},finish_reason:'stop'}]})}\n\ndata: [DONE]\n\n`);};try{await streamTaiwanChat(res,'synthetic',{model:'openrouter/free',messages:[{role:'user',content:'分析圖層'}]});assert.equal(calls.length,4);assert.ok(!res.output.includes('User Safety: safe'));assert.match(res.output,/已載入的圖層/);assert.match(res.output,/event: done/);}finally{globalThis.fetch=original;}});

test('supported optional reasoning is disabled; mandatory reasoning keeps valid effort',()=>{assert.deepEqual(finalTextOptions({supported_parameters:['reasoning'],reasoning:{mandatory:false}}),{max_tokens:4096,reasoning:{enabled:false,exclude:true}});assert.equal(finalTextOptions({supported_parameters:['reasoning'],reasoning:{mandatory:true,supported_efforts:['high','low']}}).reasoning.effort,'low');assert.equal(finalTextOptions(metadata('plain')).reasoning,undefined);});
test('truncated parse output is rejected and the next model succeeds',async()=>{let count=0;const result=await parseTransitText('請規劃比較公車與列車',base,{credential:()=> 'synthetic',fetcher:async(url,options)=>{if(url.endsWith('/models'))return Response.json({data:['cut','complete'].map(metadata)});count++;return Response.json({choices:[{finish_reason:count===1?'length':'stop',message:{content:JSON.stringify({patch:{origin:'宜蘭',destination:'臺北'},intent:'plan',needsClarification:false,questions:[],explanation:'已理解'})}}]});}});assert.equal(result.model,'complete');assert.equal(count,2);});
