import test from 'node:test';import assert from 'node:assert/strict';
import {createOfficialTransit,TRA_ODS_LIST,TRA_ODS_STATIONS} from '../overlay/server/providers/officialTransit.js';
import {normalizeTripRequest} from '../overlay/server/providers/tdxTrip.js';
import {transitMessageIntent} from '../overlay/src/taiwan/transitAssistant.js';
import {createOfficialRailGeometry} from '../overlay/server/providers/officialRailGeometry.js';
const now=()=>Date.parse('2026-10-07T00:00:00Z');
const stations=[{stationCode:'7190',stationName:'宜蘭',gps:'24.75462 121.75791'},{stationCode:'7160',stationName:'羅東',gps:'24.67795 121.77424'},{stationCode:'1000',stationName:'臺北',gps:'25.04771 121.51784'},...Array.from({length:100},(_,i)=>({stationCode:String(8000+i),stationName:'fixture '+i,gps:'23.5 120.5'}))];
const point=(id)=>{const s=stations.find(s=>s.stationCode===id);const [lat,lon]=s.gps.split(' ').map(Number);return {id,name:s.stationName,lat,lon};};
const train=(number,ids,times,kind='1131')=>({Type:'1',Train:number,CarClass:kind,TimeInfos:ids.map((id,i)=>({Station:id,Order:String(i+1),ARRTime:times[i],DEPTime:times[i]}))});
const rows=[train('4146',['7190','7160'],['09:51:00','10:02:00']),train('411',['7160','1000'],['10:55:00','12:25:00'],'110G'),...Array.from({length:100},()=>({Type:'0',Train:'fixture',CarClass:'1130',TimeInfos:[]}))];
function fixture({badLink=false,robots='',changed=false}={}){const fetched=[];const provider=createOfficialTransit({now,credential:()=>'',railGeometry:{route:async(from,to)=>({geometry:{type:'LineString',coordinates:[[from.lon,from.lat],[to.lon,to.lat]]},geometryStatus:'ready',geometrySource:'TEST FIXTURE'})},fetcher:async url=>{fetched.push(url);if(url.endsWith('robots.txt'))return robots?new Response(robots):new Response('',{status:404});if(url===TRA_ODS_STATIONS)return Response.json(stations);if(url===TRA_ODS_LIST)return new Response(`<a href="${badLink?'https://example.com/unreviewed':'/tra-ods-web/ods/download/dataResource/exceptionDataResource/'+ 'a'.repeat(32)}">20261008.json</a>`);return Response.json(changed?{Unexpected:rows}:{TrainInfos:rows,UpdateTime:'2026-10-07 03:40:05'});}});return {provider,fetched};}
const request=()=>normalizeTripRequest({origin:point('7190'),destination:point('1000'),waypoints:[{location:point('7160'),stayDurationMinutes:30}],timeMode:'departure',departureTime:'2026-10-08T09:00:00+08:00',arrivalDeadline:'2026-10-08T13:00:00+08:00',allowedModes:['TRA','WALK'],farePreference:{passengerProfiles:[{type:'adult',quantity:1},{type:'child',quantity:1},{type:'student',quantity:1}]}},now());
test('contextual reasons and crawler followups always enter the transit workflow',()=>{const state={hasRequest:true,active:true};assert.equal(transitMessageIntent('TDX未回傳方案，原因是？',state),'diagnose');assert.equal(transitMessageIntent('可以用爬蟲解決嗎',state),'fallback');assert.equal(transitMessageIntent('?',state),'status');assert.equal(transitMessageIntent('請爬蟲查核官方地形公告',state),null);});
test('public official date-specific timetable handles a waypoint without TDX or an LLM',async()=>{const {provider,fetched}=fixture(),r=request(),stages=[];const result=await provider.plan(r,{onProgress:m=>stages.push(m)});assert.equal(result.plans.length,1);const p=result.plans[0];assert.equal(p.segments[0].trainNumber,'4146');assert.equal(p.segments[1].trainNumber,'411');assert.equal(p.geometryStatus,'ready');assert.equal(p.arrivalTime,'2026-10-08T12:25:00+08:00');assert.ok(Date.parse(p.segments[1].departureTime)-Date.parse(p.segments[0].arrivalTime)>=30*60000);assert.ok(Date.parse(p.arrivalTime)<=Date.parse(r.arrivalDeadline));assert.equal(result.request.farePreference.passengerProfiles.length,3);assert.ok(stages.some(s=>s.includes('第 2/2 段')));const before=fetched.length;await provider.plan(r);assert.equal(fetched.length,before);assert.ok(fetched.every(u=>new URL(u).host==='ods.railway.gov.tw'));});
test('unknown train code and explicit train exclusions cannot be guessed into a route',async()=>{const {provider}=fixture();const r=request();r.traTrainType='local';const result=await provider.plan(r);assert.equal(result.plans.length,0);assert.match(result.notices.join(' '),/未自行放寬/);});
test('a tighter deadline is not silently extended',async()=>{const {provider}=fixture();const r=request();r.arrivalDeadline='2026-10-08T11:00:00+08:00';const result=await provider.plan(r);assert.equal(result.plans.length,0);assert.equal(result.request.arrivalDeadline,r.arrivalDeadline);});
test('public source redirects and unreviewed listing links are rejected',async()=>{const {provider,fetched}=fixture({badLink:true});await assert.rejects(provider.timetable('2026-10-08'),/官方允許清單/);assert.ok(fetched.every(u=>!u.includes('example.com')));});
test('robots and changed schema fail visibly without fictional timetables',async()=>{const {provider}=fixture({robots:'User-agent: *\nDisallow: /tra-ods-web/'});await assert.rejects(provider.stations(),/不允許/);const other=fixture({changed:true}).provider;await assert.rejects(other.timetable('2026-10-08'),/格式驗證/);});
test('real bundled NLSC corridor passes the official station sequence and does not bridge an off-network point',async()=>{const g=createOfficialRailGeometry(),route=await g.route(point('7160'),point('1000'),[point('7190')]);assert.ok(route.geometry.coordinates.length>100);assert.match(route.geometrySource,/非營運股道/);assert.equal(await g.route({lat:22,lon:121,name:'off network'},point('1000')),null);});
