import test from 'node:test';import assert from 'node:assert/strict';import {createTransitPanel} from '../overlay/src/taiwan/transitPanel.js';
class Node{constructor(){this.dataset={};this.children=new Map();this.events=new Map();this.innerHTML='';this.textContent='';this.value='';this.hidden=false;this.classList={add(){},toggle(){}};}querySelector(key){if(!this.children.has(key))this.children.set(key,new Node());return this.children.get(key);}querySelectorAll(){return [];}addEventListener(k,f){this.events.set(k,f);}removeEventListener(k){this.events.delete(k);}}
const store=new Map();globalThis.localStorage={getItem:k=>store.get(k),setItem:(k,v)=>store.set(k,v)};
const manager={create(){return {body:new Node(),element:new Node(),setSummary(){},restore(){},show(){},hide(){},minimize(){},bringToFront(){},destroy(){}};}};
const future=new Date(Date.now()+86400000).toISOString(),request={origin:{name:'A',lat:25,lon:121},destination:{name:'B',lat:25.01,lon:121.01},timeMode:'departure',departureTime:future,farePreference:{passengerProfiles:[{type:'adult',quantity:1},{type:'child',quantity:1}]}};
test('no route presents three suggestions and does not plan again before approval',async()=>{const original=globalThis.fetch;let calls=0,proposal;globalThis.fetch=async()=>{calls++;return Response.json({plans:[],notices:['查無符合期限的官方班次']});};const panel=createTransitPanel({manager,onRecovery:p=>proposal=p});try{panel.setRequest(request);await panel.plan();assert.equal(calls,1);assert.equal(proposal.suggestions.length,3);assert.deepEqual(panel.state.farePreference.passengerProfiles,request.farePreference.passengerProfiles);await panel.confirmRecovery(proposal.id,0);assert.equal(calls,2);}finally{panel.destroy();globalThis.fetch=original;}});
test('editing invalidates an old assistant confirmation without network requests',async()=>{let proposal;const panel=createTransitPanel({manager,onRecovery:p=>proposal=p});await panel.plan();assert.equal(proposal.suggestions.length,3);panel.setRequest(request);await assert.rejects(panel.confirmRecovery(proposal.id,0),/失效/);panel.destroy();});
test('natural-language suggestion confirmation works with no prior plans',async()=>{let proposal;const panel=createTransitPanel({manager,onRecovery:p=>proposal=p});await panel.plan();assert.equal(panel.active,true);const result=await panel.handleMessage('採用建議1');assert.equal(result.editing,true);assert.equal(panel.recovery,null);panel.destroy();});

test('execution waits for explicit approval, then concludes and requests autoplay once',async()=>{const original=globalThis.fetch;let proposal,calls=[],shown=[],explained=[];const plan={id:'fixture',label:'測試',segments:[{mode:'BUS',from:{name:'A'},to:{name:'B'},fare:{amount:30}}]};globalThis.fetch=async(_url,options)=>{const data=JSON.parse(options.body);calls.push(data);return Response.json(data.action==='execute-plan'?{plans:[plan],conclusion:true}:{plans:[plan],offerId:'server-owned-offer'});};const panel=createTransitPanel({manager,onRecovery:p=>proposal=p,onPlan:(_p,o)=>shown.push(o),onExplain:r=>explained.push(r)});try{panel.setRequest(request);await panel.plan();assert.equal(calls.length,1);assert.equal(proposal.suggestions[0].action,'execute');assert.equal(shown[0].execute,false);await panel.handleMessage('按 AI 建議執行');assert.equal(calls[1].action,'execute-plan');assert.equal(calls[1].offerId,'server-owned-offer');assert.equal(calls[1].plans,undefined);assert.equal(shown[1].execute,true);assert.equal(explained.at(-1).conclusion,true);assert.equal(panel.recovery,null);}finally{panel.destroy();globalThis.fetch=original;}});
