import test from 'node:test';import assert from 'node:assert/strict';
import {transitMessageIntent,transitConfirmationIndex,rateLimitText} from '../overlay/src/taiwan/transitAssistant.js';
import {tdxLimit} from '../overlay/server/providers/tdxLimits.js';
import {registerHooks} from 'node:module';
registerHooks({resolve(specifier,context,next){if(specifier.endsWith('/taiwanCredentialStore.js')||specifier==='./taiwanCredentialStore.js')return {url:'data:text/javascript,export function getCredential(){return ""}',shortCircuit:true};return next(specifier,context);}});
const {createTdxService}=await import('../overlay/server/providers/tdxService.js');
import {createTransitPanel} from '../overlay/src/taiwan/transitPanel.js';
const state={hasRequest:true,active:true};
test('button and conversational confirmations route to one real workflow',()=>{for(const text of ['按你建議','按你建議執行','按 AI 建議執行','採用建議1','確認建議一','照你的建議做'])assert.equal(transitMessageIntent(text,state),'confirm',text);assert.equal(transitConfirmationIndex('按你建議執行'),0);assert.equal(transitConfirmationIndex('採用建議2'),1);});
test('operational follow-ups cannot fall into a text-only spatial answer',()=>{assert.equal(transitMessageIntent('好了嗎',state),'status');assert.equal(transitMessageIntent('TDX是否串接完成',state),'service');assert.equal(transitMessageIntent('我已串接TDX，票價是否由你爬蟲取得',state),'sources');assert.equal(transitMessageIntent('分析目前圖層用途',{hasRequest:false} ),null);});
test('quota countdown needs an authoritative reset and never invents midnight',()=>{const now=Date.parse('2026-10-06T02:00:00Z');const quota=tdxLimit(new Response('quota exceeded',{status:429,headers:{'retry-after':'90'}}),'quota exceeded',now);assert.equal(quota.kind,'quota');assert.equal(quota.resetAt,null);assert.match(rateLimitText(quota,now),/官方允許重試倒數：0:01:30/);assert.doesNotMatch(rateLimitText(quota,now),/官方額度恢復倒數/);const reset=tdxLimit(new Response('',{status:429,headers:{'x-ratelimit-reset':String((now+120000)/1000)}}),'quota exceeded',now);assert.match(rateLimitText(reset,now),/官方額度恢復倒數：0:02:00/);const fallback=tdxLimit(new Response('',{status:429}),'Too many requests',now);assert.match(rateLimitText(fallback,now),/本機退避，非額度恢復時間/);});
test('real HTTP throttling stays configured and prevents duplicate requests',async()=>{let calls=0;const now=Date.parse('2026-10-06T02:00:00Z'),service=createTdxService({credential:()=> 'fixture',now:()=>now,checkFarePolicy:false,fetcher:async url=>{calls++;return url.includes('/token')?Response.json({access_token:'fixture-token',expires_in:3600}):new Response('Monthly quota exceeded',{status:429,headers:{'retry-after':'120','x-ratelimit-reset':String((now+3600000)/1000)}});}});await assert.rejects(service.basic('/v2/Rail/TRA/Station',1),e=>e.code==='TDX_QUOTA_EXCEEDED'&&e.rateLimit.resetAt==='2026-10-06T03:00:00.000Z');const before=calls;await assert.rejects(service.basic('/v2/Rail/TRA/Station',1),e=>e.code==='TDX_QUOTA_EXCEEDED');assert.equal(calls,before);const status=await service.handle({action:'status'});assert.equal(status.configured,true);assert.equal(status.authenticated,true);assert.equal(status.limits[0].kind,'quota');assert.doesNotMatch(JSON.stringify(status),/fixture-token/);});
class Node{constructor(){this.dataset={};this.children=new Map();this.events=new Map();this.innerHTML='';this.textContent='';this.value='';this.hidden=false;this.classList={add(){},toggle(){}};}querySelector(k){if(!this.children.has(k))this.children.set(k,new Node());return this.children.get(k);}querySelectorAll(){return [];}addEventListener(k,f){this.events.set(k,f);}removeEventListener(k){this.events.delete(k);}}
globalThis.localStorage={getItem:()=>null,setItem(){}};const manager={create(){return {body:new Node(),element:new Node(),setSummary(){},restore(){},show(){},hide(){},minimize(){},bringToFront(){},destroy(){}};}};
const request={origin:{name:'A',lat:25,lon:121},destination:{name:'B',lat:25.01,lon:121.01},timeMode:'departure',departureTime:new Date(Date.now()+86400000).toISOString()};
test('past-time suggestion click performs real replan and always emits an outcome',async()=>{const original=fetch;let calls=0,proposal,explained=[];globalThis.fetch=async()=>{calls++;return Response.json({plans:[],notices:['查無符合期限的官方方案']});};const panel=createTransitPanel({manager,onRecovery:r=>proposal=r,onExplain:r=>explained.push(r)});try{panel.setRequest({...request,departureTime:new Date(Date.now()-3600000).toISOString()});await panel.plan();assert.equal(calls,0);assert.equal(proposal.suggestions[0].label,'按你建議執行');await panel.confirmRecovery(proposal.id,0);assert.equal(calls,1);assert.equal(explained.at(-1).conclusion,true);assert.equal(panel.recovery.suggestions.length,3);assert.equal(panel.recovery.suggestions[0].label,'按你建議執行');}finally{panel.destroy();globalThis.fetch=original;}});
test('work in progress cannot issue a second plan or enter a model',async()=>{const original=fetch;let release,calls=0;globalThis.fetch=()=>{calls++;return new Promise(resolve=>release=()=>resolve(Response.json({plans:[],notices:['無班次']})));};const panel=createTransitPanel({manager});try{panel.setRequest(request);const task=panel.plan();assert.equal(panel.busy,true);const result=await panel.handleMessage('採用建議1');assert.equal(result.busy,true);assert.equal(calls,1);release();await task;assert.equal(panel.busy,false);}finally{panel.destroy();globalThis.fetch=original;}});
test('map display failure preserves and automatically reports the server conclusion',async()=>{const original=fetch;let explained=[];const plan={id:'fixture',segments:[]};globalThis.fetch=async(_u,o)=>Response.json(JSON.parse(o.body).action==='execute-plan'?{plans:[plan],conclusion:true}:{plans:[plan],offerId:'fixture-offer'});const panel=createTransitPanel({manager,onExplain:r=>explained.push(r),onPlan:(_p,o)=>{if(o.execute)throw Error('renderer fixture unavailable');}});try{panel.setRequest(request);await panel.plan();await panel.handleMessage('按你建議執行');assert.equal(explained.at(-1).conclusion,true);assert.equal(explained.at(-1).animationStarted,false);assert.match(explained.at(-1).notices.join(' '),/renderer fixture/);}finally{panel.destroy();globalThis.fetch=original;}});

test('server conclusion is emitted before map preparation resolves',async()=>{const original=fetch;let explained=[],release;const plan={id:'fixture',segments:[]};globalThis.fetch=async(_u,o)=>Response.json(JSON.parse(o.body).action==='execute-plan'?{plans:[plan],conclusion:true,offerId:'offer'}:{plans:[plan],offerId:'offer'});const panel=createTransitPanel({manager,onExplain:r=>explained.push(r),onPlan:(_p,o)=>o.execute?new Promise(resolve=>release=()=>resolve({animationStarted:true})):undefined});try{panel.setRequest(request);await panel.plan();const work=panel.handleMessage('按你建議');await new Promise(resolve=>setImmediate(resolve));assert.equal(explained.at(-1).displayPending,true);assert.equal(explained.at(-1).conclusion,true);release();await work;assert.equal(explained.at(-1).animationStarted,true);}finally{panel.destroy();globalThis.fetch=original;}});
test('assistant official source crawl performs a real allowlisted fetch without TDX credentials',async()=>{const {createFareService}=await import('../overlay/server/providers/fareEngine.js');let fetched=[];const service=createFareService({basic:async()=>{throw Error('fixture no TDX');},stations:async()=>[],checkPolicy:false,fetcher:async url=>{fetched.push(url);return new Response('<html><title>官方公開票價查詢</title></html>');}});const result=await service.sources({modes:['TRA']});assert.equal(fetched.length,1);assert.equal(new URL(fetched[0]).hostname,'www.railway.gov.tw');assert.equal(result.sources[0].sourceUrl,fetched[0]);assert.match(result.sources[0].status,/已擷取/);assert.ok(result.sources[0].fetchedAt);assert.equal(result.sources[0].amount,undefined);assert.match(result.sources[0].notice,/未以此頁產生金額/);});

test('failed confirmed execution reports a conclusion and renews actionable recovery',async()=>{const original=fetch;const explained=[];const plan={id:'fixture',segments:[]};globalThis.fetch=async(_u,o)=>JSON.parse(o.body).action==='execute-plan'?Response.json({error:'fixture frequency limited',code:'TDX_RATE_LIMITED',rateLimit:{kind:'rate',retryAt:new Date(Date.now()+30000).toISOString(),authoritative:true}},{status:429}):Response.json({plans:[plan],offerId:'offer'});const panel=createTransitPanel({manager,onExplain:r=>explained.push(r)});try{panel.setRequest(request);await panel.plan();const result=await panel.confirmRecovery(panel.recovery.id,0);assert.match(result.error,/fixture frequency/);assert.equal(explained.at(-1).conclusion,true);assert.equal(panel.recovery.suggestions.length,3);assert.equal(panel.recovery.suggestions[0].label,'按你建議執行');assert.equal(panel.recovery.rateLimit.kind,'rate');assert.equal(panel.busy,false);}finally{panel.destroy();globalThis.fetch=original;}});
