import type { ProcessingModelGraph } from "@geolibre/core";
import { topologicalOrder, type DescriptorResolver } from "@geolibre/processing";

/** Render values accepted by Model Builder fields as deterministic Python literals. */
function pythonLiteral(value: unknown): string {
  if (value === null || value === undefined) return "None";
  if (typeof value === "boolean") return value ? "True" : "False";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "None";
  if (typeof value === "string") return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(pythonLiteral).join(", ")}]`;
  if (typeof value === "object") {
    return `{${Object.entries(value)
      .filter(([, item]) => item !== undefined)
      .map(([key, item]) => `${pythonLiteral(key)}: ${pythonLiteral(item)}`)
      .join(", ")}}`;
  }
  return pythonLiteral(String(value));
}

/**
 * Convert a validated Model Builder graph into a runnable GeoLibre notebook script.
 *
 * The script assumes `m` is the displayed Map containing the input layer ids.
 * Processing APIs add results to that map and return their ids; those ids carry
 * graph values into later calls just as Model Builder carries values over edges.
 */
export function modelGraphToPython(
  graph: ProcessingModelGraph,
  resolveDescriptor: DescriptorResolver,
): string {
  const ordered = topologicalOrder(graph);
  if (!ordered) throw new Error("Cannot generate Python for a model containing a loop.");
  // Resolve every tool now, while the successful run's catalog is still
  // available. The host validates again before executing the copied graph.
  for (const node of ordered) {
    if (node.kind === "tool" && !resolveDescriptor(node.provider, node.toolId)) {
      throw new Error(`Cannot generate Python for unknown tool "${node.toolId ?? ""}".`);
    }
  }
  return `# Generated by GeoLibre Model Builder.\n# Run with the model's input layers loaded in the displayed map.\n\nm.run_model_builder(${pythonLiteral(graph)})\n`;
}
