import * as Cesium from 'cesium';
import { clamp, blendAngle } from './cinematicCameraPaths.js';
import { createAerialCollisionSystem } from './aerialCollisionSystem.js';
import { createAerialSceneReadiness } from './aerialSceneReadiness.js';
import { createAerialFreeSpace } from './aerialFreeSpace.js';
import { createAerialDrone } from './aerialDrone.js';

export const CINEMATIC_MODES={handdraw:'手繪空拍軌跡',free:'自由空拍'};
const xyz=p=>[p.x,p.y,p.z],cart=p=>new Cesium.Cartesian3(...p),rad=Cesium.Math.toRadians,deg=Cesium.Math.toDegrees;

/** One camera owner. Check the entire displaced body BEFORE applying motion. */
export function createCinematicCamera({viewer,governor,beforeStart=()=>{},onStatus=()=>{},onChange=()=>{},onFinished=()=>{}}){
  const settings={mode:'handdraw',height:80,speed:12,margin:3,smoothness:.8,lookAhead:40,pitch:-20,quality:'auto'};
  let position=null,origin=null,plan=null,certificate=null,running=false,paused=false,ownsCamera=false,priorInputs=null,priorFov=null,priorTabIndex=null,frame=null,handler=null,lastTime=0,lastUpdate=0,generation=0,elapsed=0,travel=0,routeSpeed=0,verticalTarget=null,velocity=new Cesium.Cartesian3(),heading=0,pitch=rad(-20),roll=0,lookDrag=null,pending=null,preflightController=null,lastPrepare=0,warning='',lastTrail=0;
  const keys=new Set(),trail=[],controls=viewer.scene.screenSpaceCameraController,drone=createAerialDrone({viewer});let preview=null;
  const collision=createAerialCollisionSystem({viewer,excluded:()=>[drone.entity,preview],onStatus});
  const freeSpace=createAerialFreeSpace({collision});
  const readiness=createAerialSceneReadiness({viewer,governor,tilesets:()=>collision.tilesets(),onStatus});
  const emit=()=>onChange(snapshot());
  function status(message){if(message!==warning){warning=message;onStatus(message);}emit();}
  function pick(pixel){let p;try{p=viewer.scene.pickPositionSupported?viewer.scene.pickPosition(pixel):null;}catch{}const ground=viewer.scene.globe?.pick(viewer.camera.getPickRay(pixel),viewer.scene);if(p){const c=Cesium.Cartographic.fromCartesian(p),height=viewer.scene.globe?.getHeight?.(c);if(Number.isFinite(height)&&c.height<height-1)p=ground;}return p||ground;}

  function configure(values){for(const [key,value] of Object.entries(values||{})){if(key==='mode'){if(!CINEMATIC_MODES[value])throw new Error('電影空拍目前支援手繪軌跡與自由空拍');if(running||paused)throw new Error('請先停止拍攝，再切換模式');settings.mode=value;}else if(key==='quality'){if(!['auto','720p','1080p'].includes(value))throw new Error('錄影品質無效');settings.quality=value;}else if(['height','speed','margin','smoothness','lookAhead','pitch'].includes(key)){const range={height:[8,3000],speed:[1,50],margin:[3,30],smoothness:[0,1],lookAhead:[5,500],pitch:[-85,45]}[key];settings[key]=clamp(Number(value)||range[0],...range);}}emit();return {...settings};}
  function setPlan(result){if(!result?.ok||!result.validation?.safe)throw new Error('飛行計畫尚未通過安全預檢');plan=result;certificate={...result.validation,routeSnapshot:true};settings.mode='handdraw';showPreview(result.path.points);emit();}
  function showPreview(points){clearPreview();preview=viewer.entities.add({name:'空拍安全路徑預覽',polyline:{positions:points.map(cart),width:2,material:Cesium.Color.fromCssColorString('#9addff')},properties:{aerialPreview:true}});viewer.scene.requestRender();}
  function clearPreview(){if(preview)viewer.entities.remove(preview);preview=null;}
  function place(p,orientation=0){if(running||paused)throw new Error('請先停止拍攝');generation++;cancelPending();freeSpace.clear();origin=Cesium.Cartesian3.clone(p);position=Cesium.Cartesian3.clone(p);heading=orientation;drone.place(position,heading);certificate=null;emit();return position;}
  function cancelPending(){pending?.controller?.abort();pending=null;preflightController?.abort();preflightController=null;}
  async function verifyFreePosition(point,{signal}={}){
    cancelPending();const controller=new AbortController();preflightController=controller;const cancelled=()=>controller.abort();signal?.addEventListener('abort',cancelled,{once:true});if(signal?.aborted)controller.abort();
    const token=generation,radius=collision.margin({speed:settings.speed,dt:.2,margin:settings.margin})+5;
    try{const r=await freeSpace.preflight(point,{radius,speed:settings.speed,heading,signal:controller.signal});if(token!==generation||controller.signal.aborted)throw new Error('位置確認已取消，請重新確認');if(!r.safe)throw new Error(`${r.reason||r.unsafe?.[0]?.reason||'起飛周邊走廊不安全'}，請移至更高且開闊的位置`);certificate=r;status('起飛位置與六方向連續走廊已檢查；飛行中會提前檢查新方向');return r;}
    finally{signal?.removeEventListener('abort',cancelled);if(preflightController===controller)preflightController=null;}
  }

  async function confirmOrigin(options={}){if(!origin)throw new Error('請先在地圖放置無人機');return verifyFreePosition(Cesium.Cartesian3.clone(origin),options);}
  function installInputs(){priorInputs=controls.enableInputs;controls.enableInputs=false;ownsCamera=true;viewer.trackedEntity=undefined;priorFov=viewer.camera.frustum?.fov??null;priorTabIndex=viewer.canvas.tabIndex;if(viewer.canvas.tabIndex<0)viewer.canvas.tabIndex=0;viewer.canvas.focus?.({preventScroll:true});window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);window.addEventListener('blur',blur);
    handler=new Cesium.ScreenSpaceEventHandler(viewer.canvas);const start=e=>{lookDrag=e.position;},end=()=>{lookDrag=null;},look=e=>{if(!lookDrag||(!keys.has('Control')&&settings.mode!=='free'))return;heading+=(e.endPosition.x-e.startPosition.x)*.0018;pitch=clamp(pitch-(e.endPosition.y-e.startPosition.y)*.0018,rad(-85),rad(80));};for(const modifier of [undefined,Cesium.KeyboardEventModifier.CTRL]){handler.setInputAction(start,Cesium.ScreenSpaceEventType.LEFT_DOWN,modifier);handler.setInputAction(end,Cesium.ScreenSpaceEventType.LEFT_UP,modifier);handler.setInputAction(look,Cesium.ScreenSpaceEventType.MOUSE_MOVE,modifier);}
  }
  function keyDown(event){const k=event.key.length===1?event.key.toLowerCase():event.key;if(k==='Escape'){event.preventDefault();stop();return;}if(event.target?.closest?.('input,textarea,select,button,[contenteditable="true"]'))return;if(['w','s','a','d','i','k','j','l','Control'].includes(k)){event.preventDefault();keys.add(k);}}
  function keyUp(e){keys.delete(e.key.length===1?e.key.toLowerCase():e.key);}
  function blur(){keys.clear();lookDrag=null;}
  function release(){if(!ownsCamera)return;ownsCamera=false;window.removeEventListener('keydown',keyDown);window.removeEventListener('keyup',keyUp);window.removeEventListener('blur',blur);handler?.destroy();handler=null;viewer.camera.cancelFlight();viewer.camera.lookAtTransform(Cesium.Matrix4.IDENTITY);if(priorInputs!==null)controls.enableInputs=priorInputs;priorInputs=null;if(priorFov!==null&&viewer.camera.frustum)viewer.camera.frustum.fov=priorFov;priorFov=null;if(priorTabIndex!==null&&priorTabIndex!==undefined)viewer.canvas.tabIndex=priorTabIndex;priorTabIndex=null;keys.clear();lookDrag=null;}
  function setCamera(){viewer.camera.setView({destination:position,orientation:{heading,pitch,roll}});drone.move(position,heading);drone.show(false);if(settings.mode==='handdraw'&&plan&&viewer.camera.frustum?.fov!==undefined)viewer.camera.frustum.fov=rad(plan.plan.fov);viewer.scene.requestRender();}
  function track(now){if(!position||now-lastTrail<200)return;lastTrail=now;const c=Cesium.Cartographic.fromCartesian(position);trail.push([deg(c.longitude),deg(c.latitude),c.height,elapsed]);if(trail.length>18000)trail.splice(1,1);}
  function prepareAhead(points,radius){
    if(pending||performance.now()-lastPrepare<250)return;const token=generation,controller=new AbortController();lastPrepare=performance.now();
    const job={controller,promise:null};pending=job;
    const validate=settings.mode==='free'?freeSpace.prepare:collision.validate;
    job.promise=validate(points,{radius:radius+5,signal:controller.signal}).then(result=>{if(token!==generation||controller.signal.aborted)return;if(result.safe){if(settings.mode!=='free')certificate=result;warning='';emit();}else status(result.reason||result.unsafe?.[0]?.reason||'前方路徑不安全，將保留在已檢查範圍');}).catch(error=>{if(token===generation&&!controller.signal.aborted)status(error.message);}).finally(()=>{if(pending===job)pending=null;});
  }

  function freeNext(dt){const strafe=Number(keys.has('d'))-Number(keys.has('a'));let vertical=Number(keys.has('i'))-Number(keys.has('k'));if(vertical)verticalTarget=null;else if(verticalTarget!==null){const difference=verticalTarget-Cesium.Cartographic.fromCartesian(position).height;if(Math.abs(difference)<.8){verticalTarget=null;status('已完成安全升降');}else vertical=clamp(difference*.1,-1,1);}settings.speed=clamp(settings.speed+(Number(keys.has('j'))-Number(keys.has('l')))*6*dt,1,50);pitch=clamp(pitch,rad(-85),rad(80));roll*=Math.exp(-dt*3);
    const forward=Number(keys.has('w'))-Number(keys.has('s')),speed=settings.speed,local=new Cesium.Cartesian3((Math.sin(heading)*forward+Math.cos(heading)*strafe)*speed,(Math.cos(heading)*forward-Math.sin(heading)*strafe)*speed,vertical*Math.min(speed,10)),matrix=Cesium.Transforms.eastNorthUpToFixedFrame(position),desired=Cesium.Matrix4.multiplyByPointAsVector(matrix,local,new Cesium.Cartesian3()),factor=1-Math.exp(-dt*(2.5-settings.smoothness*1.5));velocity=Cesium.Cartesian3.lerp(velocity,desired,factor,new Cesium.Cartesian3());return Cesium.Cartesian3.add(position,Cesium.Cartesian3.multiplyByScalar(velocity,dt,new Cesium.Cartesian3()),new Cesium.Cartesian3());}
  function upcoming(distanceAhead){const points=[Cesium.Cartesian3.clone(position)];for(let d=travel;d<Math.min(plan.path.total,travel+distanceAhead);d+=2)points.push(cart(plan.path.sample(d)));points.push(cart(plan.path.sample(Math.min(plan.path.total,travel+distanceAhead))));return points;}
  function tick(now){if(!running)return;frame=requestAnimationFrame(tick);if(!lastTime){lastTime=now;return;}lastTime=now;if(now-lastUpdate<(governor?.pressured?60:30))return;const step=Math.min(.2,Math.max(.001,(now-lastUpdate)/1000));lastUpdate=now;elapsed+=step;
    let next;const speed=Cesium.Cartesian3.magnitude(velocity);let radius=collision.margin({speed:settings.mode==='handdraw'?plan.plan.speed:speed,dt:step,margin:settings.margin});
    if(settings.mode==='free'){
      next=freeNext(step);const actualSpeed=Cesium.Cartesian3.magnitude(velocity);radius=collision.margin({speed:actualSpeed,dt:step,margin:settings.margin});
      const movement=Cesium.Cartesian3.subtract(next,position,new Cesium.Cartesian3()),length=Cesium.Cartesian3.magnitude(movement);
      if(length>.001){
        const direction=Cesium.Cartesian3.normalize(movement,new Cesium.Cartesian3()),lookAhead=Math.max(12,settings.speed*4),available=freeSpace.distanceAhead(position,direction,radius,lookAhead),projection=Cesium.Cartesian3.add(position,Cesium.Cartesian3.multiplyByScalar(direction,lookAhead,new Cesium.Cartesian3()),new Cesium.Cartesian3());
        // Start loading well before the verified boundary. Keep the old forward,
        // reverse and vertical corridors while extending a new direction.
        if(available<lookAhead*.85)prepareAhead([position,projection],radius);
        const deceleration=Math.max(3,settings.speed*.65),safeSpeed=Math.sqrt(2*deceleration*Math.max(0,available-.5));
        if(actualSpeed>safeSpeed){velocity=Cesium.Cartesian3.multiplyByScalar(velocity,safeSpeed/actualSpeed,new Cesium.Cartesian3());next=Cesium.Cartesian3.add(position,Cesium.Cartesian3.multiplyByScalar(velocity,step,new Cesium.Cartesian3()),new Cesium.Cartesian3());}
        const check=collision.checkSweep(position,next,{radius,certificate:freeSpace.certificates});
        if(!check.safe){status(check.reason);velocity=new Cesium.Cartesian3();next=position;}else if(available<1){status('已接近已檢查範圍，正提前準備新方向資料');}else if(!pending){warning='';}
      }
    }

    else{const remaining=plan.path.total-travel,targetSpeed=Math.min(plan.plan.speed,Math.sqrt(Math.max(0,2*plan.plan.acceleration*remaining)));routeSpeed+=clamp(targetSpeed-routeSpeed,-plan.plan.acceleration*step,plan.plan.acceleration*step);const nextTravel=remaining<.05?plan.path.total:Math.min(plan.path.total,travel+routeSpeed*step);next=cart(plan.path.sample(nextTravel));const check=collision.checkSweep(position,next,{radius,certificate});if(!check.safe){routeSpeed=0;status(check.reason);if(check.status==='UNKNOWN')prepareAhead(upcoming(Math.max(20,plan.plan.speed*3)),radius);else stop();return;}travel=nextTravel;const look=cart(plan.path.sample(Math.min(plan.path.total,travel+plan.plan.lookAhead))),direction=Cesium.Cartesian3.subtract(look,next,new Cesium.Cartesian3()),inverse=Cesium.Matrix4.inverseTransformation(Cesium.Transforms.eastNorthUpToFixedFrame(next),new Cesium.Matrix4()),local=Cesium.Matrix4.multiplyByPointAsVector(inverse,direction,new Cesium.Cartesian3());if(!keys.has('Control')){heading=blendAngle(heading,Math.atan2(local.x,local.y),1-Math.exp(-step*4));pitch=blendAngle(pitch,rad(plan.plan.pitch),1-Math.exp(-step*3));}roll=rad(plan.plan.roll);}
    position=Cesium.Cartesian3.clone(next);setCamera();track(now);emit();if(settings.mode==='handdraw'&&travel>=plan.path.total){status('已完成手繪空拍軌跡的拍攝');stop();}
  }
  async function play(){if(running)return {ok:true};const token=++generation;if(paused){const resumePoints=settings.mode==='handdraw'?plan.path.points:[position];const resumeRadius=settings.mode==='handdraw'?plan.validation.radius:collision.margin({margin:settings.margin})+5;const check=settings.mode==='free'?await verifyFreePosition(Cesium.Cartesian3.clone(position)):await collision.validate(resumePoints,{radius:resumeRadius});if(token!==generation)throw new Error('拍攝啟動已取消');if(!check.safe)throw new Error(check.reason||'目前位置已不安全，請停止拍攝');certificate=settings.mode==='handdraw'?{...check,routeSnapshot:true}:check;paused=false;running=true;window.dispatchEvent(new CustomEvent('gev-tw:aerial-capture-ui',{detail:{active:true}}));installInputs();lastTime=0;lastUpdate=performance.now();frame=requestAnimationFrame(tick);emit();return {ok:true};}
    if(settings.mode==='free'){if(!origin||!certificate?.safe)throw new Error('請先放置並確認無人機起飛位置');const radius=collision.margin({speed:settings.speed,dt:.2,margin:settings.margin});if(!freeSpace.contains(origin,origin,radius))await confirmOrigin();}else{if(!plan?.ok)throw new Error('請先確認手繪軌跡並完成拍攝規劃');if(plan.validation.signature!==collision.signature())throw new Error('圖資已變動，請重新執行安全檢查');certificate={...plan.validation,routeSnapshot:true};}
    if(token!==generation)throw new Error('拍攝啟動已取消');await beforeStart();readiness.acquire();if(token!==generation)throw new Error('拍攝啟動已取消');cancelPending();position=settings.mode==='free'?Cesium.Cartesian3.clone(origin):cart(plan.path.sample(0));origin=Cesium.Cartesian3.clone(position);velocity=new Cesium.Cartesian3();travel=0;routeSpeed=0;elapsed=0;trail.length=0;pitch=rad(settings.mode==='handdraw'?plan.plan.pitch:settings.pitch);clearPreview();installInputs();running=true;paused=false;window.dispatchEvent(new CustomEvent('gev-tw:aerial-capture-ui',{detail:{active:true}}));lastTime=0;lastUpdate=performance.now();lastPrepare=performance.now();warning='';setCamera();track(performance.now());window.dispatchEvent(new CustomEvent('gev-tw:aerial-priority',{detail:{active:true,recording:true}}));frame=requestAnimationFrame(tick);status('拍攝中；Esc 停止。資料不足或障礙衝突時保守懸停');return {ok:true};}
  function pause(){if(!running)return;generation++;cancelPending();running=false;paused=true;if(frame!==null)cancelAnimationFrame(frame);frame=null;release();window.dispatchEvent(new CustomEvent('gev-tw:aerial-capture-ui',{detail:{active:false}}));drone.show();status('已暫停運鏡');}
  function focusDrone({distance=40}={}){if(!position||running||paused)return false;distance=clamp(Number(distance)||40,10,2000);viewer.camera.cancelFlight();viewer.camera.lookAt(position,new Cesium.HeadingPitchRange(heading,-Math.atan(.6),distance*Math.sqrt(1.36)));viewer.camera.lookAtTransform(Cesium.Matrix4.IDENTITY);viewer.scene.requestRender();return true;}
  function stop({clear=false,silent=false}={}){const wasActive=running||paused;generation++;running=false;paused=false;cancelPending();verticalTarget=null;if(frame!==null)cancelAnimationFrame(frame);frame=null;release();readiness.release();window.dispatchEvent(new CustomEvent('gev-tw:aerial-capture-ui',{detail:{active:false}}));drone.show();if(wasActive&&settings.mode==='free'&&!clear)focusDrone();if(clear){freeSpace.clear();clearPreview();plan=null;certificate=null;drone.destroy();origin=null;position=null;}if(wasActive)onFinished(snapshot({includeTrail:true}));window.dispatchEvent(new CustomEvent('gev-tw:aerial-priority',{detail:{active:false}}));if(!silent)emit();}
  function snapshot({includeTrail=false}={}){const c=position?Cesium.Cartographic.fromCartesian(position):null;return {settings:{...settings},running,paused,elapsed,travel,speed:settings.mode==='handdraw'?routeSpeed:Cesium.Cartesian3.magnitude(velocity),heading:deg(heading),height:c?.height??null,position:position?xyz(position):null,origin:origin?xyz(origin):null,warning,freeCoverageCertificates:settings.mode==='free'?freeSpace.size:0,preparing:!!pending,trail:includeTrail?trail.map(p=>p.slice()):[],plan:plan?.plan??null};}
  function requestHeight({value,delta=20}){if(!position||settings.mode!=='free'||(!running&&!paused))throw new Error('請先開始自由空拍拍攝');const current=Cesium.Cartographic.fromCartesian(position).height,base=Cesium.Cartographic.fromCartesian(origin).height-settings.height;verticalTarget=clamp(Number.isFinite(value)?base+value:current+delta,-400,15000);status(`已設定安全升降目標 ${Math.round(verticalTarget)} 公尺；遇到障礙會阻擋`);return {ok:true,heightTarget:verticalTarget};}
  return {configure,snapshot,setPlan,place,confirmOrigin,showPreview,clearPreview,pick,collision,drone,async prepareScene(points,options){const result=await readiness.prepare(points,options);window.dispatchEvent(new CustomEvent('gev-tw:aerial-priority',{detail:{active:true,preparing:true}}));await new Promise(resolve=>setTimeout(resolve,150));return result;},releaseScene(){readiness.release();window.dispatchEvent(new CustomEvent('gev-tw:aerial-priority',{detail:{active:false}}));},play,pause,stop,requestHeight,focusDrone,get active(){return running||paused;},destroy(){stop({clear:true});collision.destroy();readiness.destroy();}};
}
