import {db} from './db.js';
const VERSION=1;
const namespace=()=>{let id=localStorage.getItem('gev.tw.recordNamespace');if(!id){id=crypto.randomUUID();localStorage.setItem('gev.tw.recordNamespace',id);}return id;};
export async function recordIndexRequest(body,signal){const response=await fetch('/api/taiwan/ai/record-index',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,namespace:namespace()}),signal});const value=await response.json();if(!response.ok)throw Error(value.error||'紀錄索引服務無法使用');return value;}
export function recordTier(createdAt){const age=Date.now()-Date.parse(createdAt);return age<=86400000?'Hot（24小時內）':age<=30*86400000?'Warm（30天內）':'Cold（較早紀錄）';}
export async function summarizeRecord(record){
  const raw=String(record.markdown||'').replace(/data:[^,\s]+;base64,[A-Za-z0-9+/=_-]+/g,'[影像附件索引]'),lines=raw.split(/\r?\n/).map(x=>x.trim()).filter(x=>x&&!/^!\[|^```|^\|\s*[-:| ]+\|$/.test(x));
  const ranked=lines.map((text,i)=>({text,i,rank:/結論|查核|結果|來源|錯誤|未完成|建議|班次|票價|數量|時間|攝影機/.test(text)?2:/^#|^\|/.test(text)?1:0})).sort((a,b)=>b.rank-a.rank||a.i-b.i);let length=0;const chosen=[];
  for(const line of ranked){const text=line.text.slice(0,400);if(length+text.length>2200)continue;chosen.push({...line,text});length+=text.length;if(chosen.length>=24)break;}
  const eventMetadata=(record.cctvResults||[]).slice(-50).map(x=>({cameraId:x.cameraId||x.cameraName||'',cameraName:x.cameraName||'',capturedAt:x.capturedAt,eventType:x.eventType||x.congestion?.label||'辨識',counts:x.counts||{},source:x.source||'',confidence:x.confidence??null,requestId:x.requestId||''}));
  const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw)),firstCctv=record.cctvResults?.[0],type=record.cctvResults?.length?'cctv':record.media?'aerial':'chat';
  return {id:record.id,filename:record.filename,createdAt:record.createdAt,messageCount:record.messageCount,type,location:firstCctv?.cameraName||'',project:record.project||'',cameraId:firstCctv?.cameraId||firstCctv?.cameraName||'',events:[...new Set(eventMetadata.map(x=>x.eventType))],eventMetadata,summary:chosen.sort((a,b)=>a.i-b.i).map(x=>x.text).join('\n'),hash:[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join(''),rawCharacters:raw.length,frameCount:record.frames?.length||0,hasVideo:!!record.media?.video,attachments:(record.attachments||[]).map(x=>({filename:x.filename})),version:VERSION,serverIndexed:false};
}
export async function indexRecord(record){const meta=await summarizeRecord(record);await db.recordIndex.put(meta);try{await recordIndexRequest({action:'upsert',records:[meta]});await db.recordIndex.update(meta.id,{serverIndexed:true});}catch{/* Browser metadata remains usable offline. */}return meta;}
let migration;
/** Read legacy full text once for migration, in small batches; subsequent queries only read L2 metadata. */
export function ensureRecordIndex(onProgress=()=>{},signal){if(!migration)migration=(async()=>{const ids=await db.chatRecords.toCollection().primaryKeys();let done=0;for(let at=0;at<ids.length;at+=25){signal?.throwIfAborted();const batch=ids.slice(at,at+25),metas=await db.recordIndex.bulkGet(batch),pending=[];for(let i=0;i<batch.length;i++){let meta=metas[i];if(!meta||meta.version!==VERSION){const raw=await db.chatRecords.get(batch[i]);if(!raw)continue;meta=await summarizeRecord(raw);await db.recordIndex.put(meta);}if(!meta.serverIndexed)pending.push(meta);}if(pending.length)try{await recordIndexRequest({action:'upsert',records:pending},signal);await db.recordIndex.bulkPut(pending.map(x=>({...x,serverIndexed:true})));}catch(error){signal?.throwIfAborted();}done+=batch.length;onProgress({stage:'紀錄索引',completed:done,total:ids.length,message:`紀錄索引已確認 ${done}/${ids.length} 筆；舊全文只於首次建立摘要讀取。`});await new Promise(r=>setTimeout(r,0));}return ids.length;})().finally(()=>{migration=null;});return migration;}
export async function retrieveRecords({ids,query='',limit=10,signal,onProgress=()=>{},filters={}}={}){
  await ensureRecordIndex(onProgress,signal);signal?.throwIfAborted();
  try{return await recordIndexRequest({action:'search',ids,query,limit,...filters},signal);}catch(error){signal?.throwIfAborted();const all=ids?(await db.recordIndex.bulkGet(ids)).filter(Boolean):await db.recordIndex.toArray(),terms=query.split(/[\s，。；：、]+/).filter(x=>x.length>=2),filtered=all.filter(r=>(!filters.type||r.type===filters.type)&&(!filters.from||r.createdAt>=filters.from)&&(!filters.to||r.createdAt<=filters.to)&&(!filters.location||r.location.includes(filters.location))&&(!filters.project||r.project.includes(filters.project))&&(!filters.event||r.events?.some(x=>x.includes(filters.event))));filtered.sort((a,b)=>terms.filter(t=>b.summary.includes(t)).length-terms.filter(t=>a.summary.includes(t)).length||b.createdAt.localeCompare(a.createdAt));return {records:filtered.slice(0,Math.min(10,limit)),total:filtered.length,engine:'瀏覽器摘要索引（SQLite 暫時不可用）',warning:error.message};}
}
export async function deleteRecordIndex(id){await db.recordIndex.delete(id);try{await recordIndexRequest({action:'delete',id});}catch{/* Offline index is independent from the original export. */}}
