import {markdownTable} from './selectedLayerAnalysis.js';
import {TRANSIT_MODES,timeText} from './transitPlanning.js';
const fare=p=>Number.isFinite(p.totalFare)?`NT$${p.totalFare}`:Number.isFinite(p.estimatedTotal)?`估算 NT$${p.estimatedTotal}`:'部分費用未知，無完整總額';
export function transitResultTables(result,fareInfo){
  const plans=result.plans||[],notices=[...new Set([...(result.questions||[]),...(result.notices||[])])];
  const table=markdownTable(['方案','出發','抵達','旅程時間','轉乘','步行','總交通費'],plans.map(p=>[p.label||p.id,timeText(p.departureTime),timeText(p.arrivalTime),Number.isFinite(p.durationSeconds)?`${Math.ceil(p.durationSeconds/60)} 分鐘`:'未提供',p.transfers??'未知',Number.isFinite(p.walkDistanceMeters)?`${Math.round(p.walkDistanceMeters)} 公尺`:'未知',fare(p)]));
  const details=plans.map(p=>`### ${p.label||p.id}\n\n${markdownTable(['段次','運具／車次／車種','起點 → 終點','出發 → 抵達','票價','班次狀態'],(p.segments||[]).map((s,i)=>[i+1,[TRANSIT_MODES[s.mode]||s.mode,s.trainNumber,s.transportType||s.routeName].filter(Boolean).join(' '),`${s.from?.name||''} → ${s.to?.name||''}`,`${timeText(s.departureTime)} → ${timeText(s.arrivalTime)}`,Number.isFinite(s.fare?.amount)?`${s.fare.estimated?'估算 ':''}NT$${s.fare.amount}`:'未知',s.realtimeStatus==='dynamic'?'動態資料':'表定／非即時']))}\n\n#### 乘客、座位與票價來源\n\n${markdownTable(['段次','票種、座位、金額與驗證依據'],(p.segments||[]).map((s,i)=>[i+1,fareInfo(s)]))}\n\n${[...new Set(p.notices||[])].map(n=>'- '+n).join('\n')}\n\n來源：${(p.sources||[]).map((s,i)=>/^https:\/\//.test(s)?`[官方來源 ${i+1}](${s})`:s).join('、')}`).join('\n\n');
  const comparisons=result.comparisons?.length?'\n\n### 費用／時間比較（結構化計算）\n\n'+markdownTable(['比較方案','費用差','節省時間'],result.comparisons.map(c=>[`${plans.find(p=>p.id===c.b)?.label||c.b} 相較 ${plans.find(p=>p.id===c.a)?.label||c.a}`,`${c.extraAmount>=0?'增加':'節省'} NT$${Math.abs(c.extraAmount)}`,`${c.savedMinutes} 分鐘`])):'';
  return `## ${result.conclusion?'規劃結論':'AI 智慧大眾運輸規劃結果'}\n\n${notices.map(n=>'- '+n).join('\n')}\n\n${plans.length?table+'\n\n'+details:'目前沒有符合條件且可核實的完整方案；原因與可點擊修正建議會一併回報。'}${comparisons}\n\n- ${result.displayPending?'班次與票價已查核，正在準備地圖。':result.animationStarted?'3D 旅程行進示意已開始。':'取得方案後可點「按你建議執行」啟動行進示意。'}\n- 行程模擬為規劃路徑推算，不是車輛即時位置。含估算的票價已列明依據，不是正式報價。`;
}
