/** Reviewed public sources. Adding an operator requires a parser and source review. */
export const OfficialFareSourceRegistry=Object.freeze([
  {id:'tdx',modes:['TRA','HSR','BUS','METRO','LRT'],origin:'https://tdx.transportdata.tw',paths:/^\/api\/basic\/v2\/(Rail|Bus)\//,type:'official-api',priority:1,policy:'TDX 會員資料服務；遵守帳號存取頻率'},
  {id:'tra',modes:['TRA'],origin:'https://www.railway.gov.tw',paths:/^\/tra-tip-web\/tip\/tip001\/tip114\/query$/,type:'official-web',priority:3,policy:'公開票價試算；僅查詢，不訂票；robots 檢查'},
  {id:'trtc',modes:['METRO'],origin:'https://web.metro.taipei',paths:/^\/pages2026\/(?:WebRouteStation\/(?:BR|BL|R|G|O|Y)|WebStation\/\d{3}(?:\/8)?)$/,type:'official-web',priority:3,policy:'公開票價及乘車時間表；robots 檢查'},
  {id:'hsr',modes:['HSR'],origin:'https://en.thsrc.com.tw',paths:/^\/ArticleContent\/(?:4db23462-3589-4f0e-8158-29f5ccfe3117|4c3efc1d-e6df-4bfd-97b4-52e89f79ee5c)$/,type:'official-web',priority:3,policy:'公開票價表；robots 檢查'},
  {id:'youbike',modes:['BIKE'],origin:'https://www.youbike.com.tw',paths:/^\/region\/(?:taipei|newtaipei|taoyuan|hsinchu|miaoli|taichung|changhua|chiayi|tainan|kaohsiung|pingtung|taitung)\/rate\/$/,type:'official-web',priority:3,policy:'公開收費方式；不假設會員補助；robots 檢查'},
]);
export function officialFareSource(url){let u;try{u=new URL(url);}catch{return null;}return !u.username&&!u.password&&!u.hash&&!u.search?OfficialFareSourceRegistry.find(r=>u.origin===r.origin&&r.paths.test(u.pathname))||null:null;}
export function robotsAllows(body,path,agent='GodsEyeTaiwanFare'){
  const groups=[];let group=null,hasRules=false;
  for(const raw of body.split(/\r?\n/)){const line=raw.replace(/#.*/,'').trim(),m=line.match(/^([^:]+):\s*(.*)$/);if(!m)continue;const key=m[1].toLowerCase(),v=m[2].trim();if(key==='user-agent'){if(!group||hasRules){group={agents:[],rules:[],delay:0};groups.push(group);hasRules=false;}group.agents.push(v.toLowerCase());}else if(group&&['allow','disallow'].includes(key)){hasRules=true;if(v)group.rules.push({allow:key==='allow',path:v});}else if(group&&key==='crawl-delay')group.delay=Math.max(group.delay,Number(v)||0);}
  const specific=groups.filter(g=>g.agents.some(a=>a!=='*'&&agent.toLowerCase().includes(a))),selected=specific.length?specific:groups.filter(g=>g.agents.includes('*'));
  const rules=selected.flatMap(g=>g.rules).filter(r=>{const pattern=r.path.replace(/[.+?^{}()|[\]\\]/g,'\\$&').replaceAll('*','.*').replace(/\$$/,'$');try{return new RegExp('^'+pattern).test(path);}catch{return false;}}).sort((a,b)=>b.path.length-a.path.length||Number(b.allow)-Number(a.allow));
  return {allowed:rules[0]?.allow!==false,delayMs:Math.max(1000,...selected.map(g=>g.delay*1000))};
}
export function createOfficialFareFetcher({fetcher=fetch,now=Date.now}={}){
  const policies=new Map(),queues=new Map(),last=new Map();
  async function policy(origin,signal){const old=policies.get(origin);if(old&&now()-old.at<3600000)return old;const response=await fetcher(`${origin}/robots.txt`,{redirect:'error',signal:AbortSignal.any([signal,AbortSignal.timeout(5000)].filter(Boolean)),headers:{'User-Agent':'GodsEyeTaiwanFare/1.0'}});let body='';if(response.status===404){await response.body?.cancel();}else{if(!response.ok||Number(response.headers?.get('content-length'))>100000){await response.body?.cancel();throw Error('無法確認官方網站 robots 政策，保留最近驗證資料');}body=await response.text();if(body.length>100000)throw Error('robots 政策超過處理上限');}const r={at:now(),body};policies.set(origin,r);return r;}
  return async(url,options={})=>{const source=officialFareSource(url);if(!source||source.type!=='official-web')throw Error('票價來源不在官方允許清單');const u=new URL(url),p=await policy(u.origin,options.signal),rule=robotsAllows(p.body,u.pathname);if(!rule.allowed)throw Error('官方網站 robots 不允許擷取此票價頁');const prior=queues.get(u.origin)||Promise.resolve();const task=prior.catch(()=>{}).then(async()=>{options.signal?.throwIfAborted();const delay=Math.max(0,(last.get(u.origin)||0)+rule.delayMs-now());if(delay)await new Promise((resolve,reject)=>{const signal=options.signal,done=()=>{clearTimeout(timer);signal?.removeEventListener('abort',stop);resolve();},stop=()=>{clearTimeout(timer);signal?.removeEventListener('abort',stop);reject(signal.reason);},timer=setTimeout(done,delay);signal?.addEventListener('abort',stop,{once:true});});last.set(u.origin,now());return fetcher(url,{...options,redirect:'error',headers:{'User-Agent':'GodsEyeTaiwanFare/1.0',...options.headers}});});queues.set(u.origin,task.then(()=>{},()=>{}));return task;};
}
